FoxConcept/Models/ViewModels/Recovery/EventViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using FoxConcept.Models.DALModels;

namespace FoxConcept.Models.ViewModels.Recovery
{
    public class EventTableListViewModel
    {
        public List<EventDetailsViewModel> events { get; set; }

        //Filters
        [Display(Name = "From")]
        public DateTime StartDate { get; set; }
        [Display(Name = "To")]
        public DateTime EndDate { get; set; }

        public string EventNameSearch { get; set; }

        [Display(Name = "Orgenizational Units")]
        public IEnumerable<EntityDropDown> Ous { get; set; }

        [Display(Name = "Organizational Units")]
        public List<int> ou_codes { get; set; }

        [Display(Name = "Training Programs")]
        public IEnumerable<EntityDropDown> Tps { get; set; }

        [Display(Name = "Training Programs")]
        public List<int> tps_code { get; set; }

        [Display(Name = "Activity Type")]
        public IEnumerable<EntityDropDown> ActivityTypes { get; set; }

        [Display(Name = "Activity Type")]
        public List<int> act_code { get; set; }

        [Display(Name = "Required Physical Resources")]
        public IEnumerable<EntityDropDown> PhysicalResourceTypes { get; set; }

        [Display(Name = "Required Physical Resources")]
        public List<int> phy_code { get; set; }

        [Display(Name = "Required Human Resources")]
        public IEnumerable<EntityDropDown> HumanResouceTypes { get; set; }

        [Display(Name = "Required Human Resources")]
        public List<int> hr_code { get; set; }

        public EventTableListViewModel()
        {
            StartDate = DateTime.Now.AddMonths(-1);
            EndDate = DateTime.Now.AddMonths(1);
        }


    }

    [Serializable]
    public class EventDetailsViewModel
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public int TrainingProgramID { get; set; }
        public string TrainingProgramName { get; set; }
        public int OUID { get; set; }
        public string OUName { get; set; }
        public DateTime StartTime { get; set; }
        public DateTime EndTime { get; set; }
        public int EventType { get; set; }
        public string EventTypeName { get; set; }
        public int Duration { get; set; }
        public bool Checked { get; set; }
    }

    public class EntityDropDown
    {
        public int ID { get; set; }
        public string Name { get; set; }
    }
}

FoxConcept/Models/ViewModels/Recovery/RecoveryResultsViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using FoxConcept.Infrastructure;
using LinqToExcel;

namespace FoxConcept.Models.ViewModels.Recovery
{
    public class RecoveryResultsViewModel
    {
        public List<RecoveryResult> results { get; set; }

        public RecoveryResultsViewModel()
        {
            results = new List<RecoveryResult>();

        }
    }

    public class RecoveryResult
    {
        [Display(Name = "Organizational Unit")]
        public string OrganizationlUnit { get; set; }


        [Display(Name = "Training Program")]
        public string TrainingProgram { get; set; }

        [Display(Name = "Event Name")]
        public string EventName { get; set; }

        public DateTime EventOriginalStartDate { get; set; }
        public string EventOriginalStartTime { get; set; }
        public string EventOriginalEndTime { get; set; }
        public DateTime EventNewStartDate { get; set; }
        public string EventNewStartTime { get; set; }
        public string EventNewEndTime { get; set; }
        public string PhysicalResource { get; set; }
        public string HumanResource { get; set; }
    }
}

FoxConcept/Controllers/RecoveryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Configuration;
using System.Web.Mvc;
using FoxConcept.Infrastructure;
using FoxConcept.Models;
using FoxConcept.Models.DALModels;
using FoxConcept.Models.ViewModels.Recovery;
using LinqToExcel;

namespace FoxConcept.Controllers
{
    public class RecoveryController : Controller
    {
        //
        // GET: /Recovery/

        FoxConceptEntities _FoxConceptDB = new FoxConceptEntities();
        FoxModelContainer _FoxDB = new FoxModelContainer();

        protected override void Dispose(bool disposing)
        {
            _FoxConceptDB.Dispose();
            _FoxDB.Dispose();
            base.Dispose(disposing);
        }

        public ActionResult SelectEventsForRecovery()
        {
            EventTableListViewModel model = new EventTableListViewModel();

            model.events = GetEvents(model.StartDate, model.EndDate);


            model.Tps = model.events.Select(e => new
            {
                e.TrainingProgramID,
                e.TrainingProgramName
            }).Distinct().Select(e => new EntityDropDown()
            {
                ID = e.TrainingProgramID,
                Name = e.TrainingProgramName
            }).ToList();

            model.Ous = model.events.Select(e => new { e.OUID, e.OUName }).Distinct().Select(e => new EntityDropDown()
            {
                ID = e.OUID,
                Name = e.OUName
            }).ToList();

            model.ActivityTypes =
                model.events.Select(e => new { e.EventType, e.EventTypeName }).Distinct().Select(e => new EntityDropDown()
                {
                    ID = e.EventType,
                    Name = e.EventTypeName
                }).ToList();


            model.HumanResouceTypes = GetHumanResources(model.events);

            model.PhysicalResourceTypes = GetPhysicalResources(model.events);


            return View(model);
        }


        [HttpPost]
        public ActionResult FilterEvents(EventTableListViewModel filters)
        {

            EventTableListViewModel model = new EventTableListViewModel();

            model.StartDate = filters.StartDate;
            model.EndDate = filters.EndDate;

            model.events = GetEvents(model.StartDate, model.EndDate);

            //Search by name
            if (filters.EventNameSearch != null)
            {
                model.events = model.events.Where(e => e.Name.Contains(filters.EventNameSearch)).ToList();
            }

            //Filter by OU
            if (filters.ou_codes != null && filters.ou_codes.Count() > 0)
            {
                model.events = model.events.Where(e => filters.ou_codes.Any(o => o == e.OUID)).ToList();
            }

            //Filter by TP
            if (filters.tps_code != null && filters.tps_code.Count() > 0)
            {
                model.events = model.events.Where(e => filters.tps_code.Any(o => o == e.TrainingProgramID)).ToList();
            }

            //Filter by Activity Type
            if (filters.act_code != null && filters.act_code.Count() > 0)
            {
                model.events = model.events.Where(e => filters.act_code.Any(o => o == e.EventType)).ToList();
            }


            model.Tps = model.events.Select(e => new
            {
                e.TrainingProgramID,
                e.TrainingProgramName
            }).Distinct().Select(e => new EntityDropDown()
            {
                ID = e.TrainingProgramID,
                Name = e.TrainingProgramName
            }).ToList();

            model.Ous = model.events.Select(e => new { e.OUID, e.OUName }).Distinct().Select(e => new EntityDropDown()
            {
                ID = e.OUID,
                Name = e.OUName
            }).ToList();

            model.ActivityTypes =
                model.events.Select(e => new { e.EventType, e.EventTypeName }).Distinct().Select(e => new EntityDropDown()
                {
                    ID = e.EventType,
                    Name = e.EventTypeName
                }).ToList();


            model.HumanResouceTypes = GetHumanResources(model.events);

            model.PhysicalResourceTypes = GetPhysicalResources(model.events);

            return View("SelectEventsForRecovery", model);
        }

        private List<EntityDropDown> GetHumanResources(IEnumerable<EventDetailsViewModel> events)
        {
            return (from rr in _FoxDB.DWH_ResourcesRequirements
                    join rs in _FoxDB.Bks_DWH_ResourceTypes on rr.RequirementResourceTypeID equals rs.ResourceMetaDataTypeID
                    join evt in _FoxDB.DWH_EventsBasicData on rr.EventID equals evt.Event_ID
                    where rs.ResourceTypeID == 2
                    select new { rr.RequirementResourceTypeID, rr.RequirementResourceTypeName, evt.Event_ID }).AsEnumerable().Where(r => events.Any(e => e.ID == r.Event_ID)).Select(r => new { r.RequirementResourceTypeID, r.RequirementResourceTypeName }).Distinct().Select(r => new EntityDropDown()
                    {
                        ID = r.RequirementResourceTypeID,
                        Name = r.RequirementResourceTypeName
                    }).ToList();
        }

        private List<EntityDropDown> GetPhysicalResources(IEnumerable<EventDetailsViewModel> events)
        {
            return (from rr in _FoxDB.DWH_ResourcesRequirements
                    join rs in _FoxDB.Bks_DWH_ResourceTypes on rr.RequirementResourceTypeID equals rs.ResourceMetaDataTypeID
                    join evt in _FoxDB.DWH_EventsBasicData on rr.EventID equals evt.Event_ID
                    where rs.ResourceTypeID == 1
                    select new { rr.RequirementResourceTypeID, rr.RequirementResourceTypeName, evt.Event_ID }).AsEnumerable().Where(r => events.Any(e => e.ID == r.Event_ID)).Select(r => new { r.RequirementResourceTypeID, r.RequirementResourceTypeName }).Distinct().Select(r => new EntityDropDown()
                    {
                        ID = r.RequirementResourceTypeID,
                        Name = r.RequirementResourceTypeName
                    }).ToList();
        }

        private List<EventDetailsViewModel> GetEvents(DateTime StartDate, DateTime EndDate)
        {
            return (from ev in _FoxDB.DWH_EventsBasicData
                    join act in _FoxDB.DWH_Activities on ev.EventActivity_ID
                        equals act.Activity_ID
                    join tp in _FoxDB.DWH_TrainingProgramsBasicData on ev.EventTrainingProgram_ID equals
                        tp.TrainingProgramID
                    join units in _FoxDB.Bks_DWH_OrganizationUnitsBasicData on tp.TrainingProgram_OrganizationalUnitID
                        equals units.OrganizationalUnitID
                    where ev.Event_StartTime >= StartDate && ev.Event_EndTime <= EndDate
                    orderby ev.Event_StartTime
                    select new EventDetailsViewModel()
                    {
                        ID = ev.Event_ID,
                        Name = ev.Event_Name,
                        EndTime = (DateTime)ev.Event_EndTime,
                        StartTime = (DateTime)ev.Event_StartTime,
                        OUID = units.OrganizationalUnitID,
                        OUName = units.OrganizationalUnitName,
                        TrainingProgramID = tp.TrainingProgramID,
                        TrainingProgramName = tp.TrainingProgramName,
                        EventType = (int)act.Activity_MetaDataTypeID,
                        EventTypeName = act.Activity_MetaDataTypeName,
                        Duration = (int)ev.Event_Duration
                    }).ToList();
        }
            
       [HttpPost]
        public ActionResult RecoverySettings(DateTime StartDate , DateTime EndDate, List<EventDetailsViewModel> events)
        {
           RecoverySettingsViewModel model = new RecoverySettingsViewModel();

           model.TargetStartDate = StartDate;
           model.TargetEndTime = EndDate;

           foreach (var resourceType in GetPhysicalResources(events).ToList())
           {
               ResouceAllocationSettings settings = new ResouceAllocationSettings();
               settings.ResourceID = resourceType.ID;
               settings.ResourceName = resourceType.Name;

               settings.PreferedResource =
                   _FoxDB.Resources_tbl.Where(r => r.MDTypeID == settings.ResourceID && r.ObjectID != null).Select(r => new EntityDropDown()
                   {

                       ID = (int)r.ObjectID,
                       Name = r.Name
                   }).ToList();

               settings.AlternativeResources = settings.PreferedResource.ToList();

               model.ResourceAllocations.Add(settings);
           }

           foreach (var resourceType in GetHumanResources(events).ToList())
           {
               ResouceAllocationSettings settings = new ResouceAllocationSettings();
               settings.ResourceID = resourceType.ID;
               settings.ResourceName = resourceType.Name;
               settings.PreferedResource =
                   _FoxDB.Resources_tbl.Where(r => r.MDTypeID == settings.ResourceID && r.ObjectID != null).Select(r => new EntityDropDown()
                   {
                       ID = (int)r.ObjectID,
                       Name = r.Name
                   }).ToList();

               settings.AlternativeResources = settings.PreferedResource.ToList();

               model.ResourceAllocations.Add(settings);
           }

           model.Goals = model.GetAvailableGoals();
           model.SchedulingBusinessRules = _FoxConceptDB.SchedulingBusinessRules.Where(b => b.Optional == true).ToList();

            return View(model);
        }


        public ActionResult GetRecoveryResults()
        {
            // Need to install: https://www.microsoft.com/en-us/download/confirmation.aspx?id=23734

FoxConcept/Views/Recovery/GetRecoveryResults.cshtml
@model FoxConcept.Models.ViewModels.Recovery.RecoveryResultsViewModel
@{
    ViewBag.Title = "Step 3 - Confirmation";
    Layout = "~/Views/Shared/_FoxFormLayout.cshtml";
}

@section scripts
{


    <script src="@Url.Content("~/Scripts/jquery.validate.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/FormAjax.js")" type="text/javascript"></script>

    <script src="@Url.Content("~/Scripts/chosen/chosen.jquery.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/chosen/Chosen-Methods.js")" type="text/javascript"></script>
}

@section FormHeader
{
    <span>@ViewBag.Title</span>
    @*<link href="/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />*@
    <link href="/Content/dropit.css" rel="stylesheet" type="text/css" />
    <link href="/Scripts/chosen/chosen.css" rel="stylesheet" type="text/css" />
    <link href="/Content/datepicker3.css" rel="stylesheet" type="text/css" />
}


@section FormFooter
{
    <a href="http://zorro.britannica-ks.com/Resources/CourseResourceGantt/CourseResourceGanttFrameset.aspx?DisplayInactive=0&DisplaySecondary=0&RepositoryID=7907" id="FormSubmit">Confirm</a>
    <a href="javascript:history.back()">
        Back</a>
    @*<a href="#"  onclick="document.forms[0].submit()">Save</a>*@
}
@*<fieldset>
    <legend>Recovery Settings Summary</legend>
</fieldset>*@

<fieldset>
    <legend>Proposed Schedule</legend>
    <table>
        <thead>
            <tr>
                <th>Organizationl Unit</th>
                <th>Training Program</th>
                <th>Event Name</th>
                <th>Event Original Time</th>
                <th>Event New Time</th>
                <th>Resource Allocations</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var row in Model.results)
            {
                <tr>
                    <td>@row.OrganizationlUnit</td>
                    <td>@row.TrainingProgram</td>
                    <td>@row.EventName</td>
                    <td>@row.EventOriginalStartDate.ToString("MM/dd/yyyy") <span class="blue">@row.EventOriginalStartTime - @row.EventOriginalEndTime</span></td>
                    <td>@row.EventNewStartDate.ToString("MM/dd/yyyy") <span class="blue">@row.EventNewStartTime - @row.EventNewEndTime</span></td>
                    <td>@row.PhysicalResource
                        <br />
                        @row.HumanResource
                    </td>
                </tr>
            }
        </tbody>
    </table>
</fieldset>

<script type="text/javascript">
    $(function () {
        $('.datepicker').datepicker({
            format: "dd/mm/yyyy",
            todayBtn: true,
            clearBtn: true
        });


    });
</script>

FoxConcept/Views/Recovery/SelectEventsForRecovery.cshtml
@model FoxConcept.Models.ViewModels.Recovery.EventTableListViewModel
@{
    ViewBag.Title = "Step 1 - Select Events for Recovery";
    Layout = "~/Views/Shared/_FoxFormLayout.cshtml";
}




@section FormHeader
{
    <link href="/Content/dropit.css" rel="stylesheet" type="text/css" />
    <link href="/Scripts/chosen/chosen.css" rel="stylesheet" type="text/css" />
    <span>@ViewBag.Title</span>
    <script src="@Url.Content("~/Scripts/jquery.validate.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/FormAjax.js")" type="text/javascript"></script>

    <script src="@Url.Content("~/Scripts/chosen/chosen.jquery.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/chosen/Chosen-Methods.js")" type="text/javascript"></script>
}



<div id="SchedulingRulesTable" class="container ">
    <div class="TableHeader">
        @*<span>@ViewBag.Title</span>*@
    </div>
</div>

<div class="FiltersPanel">

    @using (Html.BeginForm("FilterEvents", "Recovery", FormMethod.Post))
    {

        <div class="span10">
            @Html.TextBoxFor(m => m.EventNameSearch, new { @class = "x-large" })
            @Html.ValidationMessageFor(m => m.EventNameSearch)
        </div>
        <div class="span10">
            @Html.LabelFor(m => m.StartDate, new { @class = "span10" })
            @Html.TextBoxFor(m => m.StartDate, new { @class = "x-large datepicker", @Value = Model.StartDate.ToString("MM/dd/yyyy") })
            @Html.ValidationMessageFor(m => m.EndDate)
        </div>

        <div class="span10">
            @Html.LabelFor(m => m.EndDate, new { @class = "span10" })
            @Html.TextBoxFor(m => m.EndDate, new { @class = "x-large datepicker", @Value = Model.EndDate.ToString("MM/dd/yyyy") })
            @Html.ValidationMessageFor(m => m.EndDate)
        </div>

        <div class="span10">
            @Html.LabelFor(m => m.ou_codes, new { @Class = "span10" })
            @Html.DropDownListFor(m => m.ou_codes, new SelectList(Model.Ous, "ID", "Name"), new { @class = "x-large chosen-select", @multiple = "multiple" })
            @Html.ValidationMessageFor(m => m.ou_codes)
        </div>

        <div class="span10">
            @Html.LabelFor(m => m.tps_code, new { @Class = "span10" })
            @Html.DropDownListFor(m => m.tps_code, new SelectList(Model.Tps, "ID", "Name"), new { @class = "x-large chosen-select", @multiple = "multiple" })
            @Html.ValidationMessageFor(m => m.tps_code)
        </div>
        <div class="span10">
            @Html.LabelFor(m => m.act_code, new { @Class = "span10" })
            @Html.DropDownListFor(m => m.act_code, new SelectList(Model.ActivityTypes, "ID", "Name"), new { @class = "x-large chosen-select", @multiple = "multiple" })
            @Html.ValidationMessageFor(m => m.act_code)
        </div>

        <div class="span10">
            @Html.LabelFor(m => m.hr_code, new { @Class = "span10" })
            @Html.DropDownListFor(m => m.hr_code, new SelectList(Model.HumanResouceTypes, "ID", "Name"), new { @class = "x-large chosen-select", @multiple = "multiple" })
            @Html.ValidationMessageFor(m => m.hr_code)
        </div>

        <div class="span10">
            @Html.LabelFor(m => m.phy_code, new { @Class = "span10" })
            @Html.DropDownListFor(m => m.phy_code, new SelectList(Model.PhysicalResourceTypes, "ID", "Name"), new { @class = "x-large chosen-select", @multiple = "multiple" })
            @Html.ValidationMessageFor(m => m.phy_code)
        </div>

        <div class="span10">
            <input type="submit" class="Button pull-right" style="width: 60px; margin-right: 34px;" value="Search" />
        </div>
    }


</div>
<div class="ContentPanel container scrollable height90">
    @using (Html.BeginForm("RecoverySettings", "Recovery", FormMethod.Post))
    {
        @Html.HiddenFor(m => m.StartDate)
        @Html.HiddenFor(m => m.EndDate)

        <table id="eventsTable">
            <thead>
                <tr>
                    <th>
                        <input type="checkbox" id="chkHeader" /></th>
                    <th>Organizational Unit</th>
                    <th>Training Program</th>
                    <th>Event Name</th>
                    <th>Start Time</th>
                    <th>End Time</th>
                    <th>Duration</th>
                    <th>Type</th>
                </tr>
            </thead>
            <tbody>
                
                @for(var i = 0; i < Model.events.Count(); i++)
                {
                    <tr>
                        <td>
                            @Html.HiddenFor(m => m.events[@i].ID)
                            @Html.CheckBoxFor(m => m.events[i].Checked)
                        </td>
@*                        <td>&nbsp;
                        <ul class="menu dropit">
                            <li>
                                <a href="#">
                                    <img src='/Content/Images/edit.gif' alt='Edit' /></a>
                                <ul class="dropit-submenu-left">
                                </ul>
                            </li>
                        </ul>
                        </td>*@
                        <td>@Model.events[i].OUName</td>
                        <td>@Model.events[i].TrainingProgramName</td>
                        <td>@Model.events[i].Name</td>
                        <td>@Model.events[i].StartTime.ToString("MM/dd/yyyy hh:mm")</td>
                        <td>@Model.events[i].EndTime.ToString("MM/dd/yyyy hh:mm")</td>
                        <td>@(Model.events[i].Duration / 60)H @( Model.events[i].Duration % 60)M </td>
                        <td>@Model.events[i].EventTypeName</td>
                    </tr>
                }
            </tbody>
        </table>
         <div id="multipleactions" class="yellowBar" style="  bottom: 50px; !important">
            <input type="submit" value="Next" class="regularLink" />
        </div>
    }
</div>

@section FormFooter
{
}


<script type="text/javascript">
    $(function () {
        $('.datepicker').datepicker({
            format: "dd/mm/yyyy",
            todayBtn: true,
            clearBtn: true
        });


        //Selecting All rows in the given page ones the header checkbox has chenged
        $("#chkHeader").change(function () {
            $("#eventsTable input:checkbox").prop('checked', $(this).prop('checked'));
        });

        //Dealing with checkbox change
        $("#eventsTable input:checkbox").change(function () {
            var sChecked = "";

            var list = $("#eventsTable input:checked").length;
            if (list > 0) {
                /*$("#multipleactions").show();*/
                $("#multipleactions").css('visibility', 'visible');
            } else {
                /*$("#multipleactions").hide();*/
                $("#multipleactions").css('visibility', 'hidden');
            }


            $("#eventsTable input:checked").each(function (index) {
                sChecked += $(this).attr("id").substring($(this).attr("id").indexOf("-") + 1);
                if (index !== list - 1) {
                    sChecked += ",";
                }


            });

            //$("#ordersTable input:checked").parent().parent().addClass("warning");
            //$("#ordersTable input:checkbox:not(:checked)").parent().parent().removeClass("warning");
            $("#eventsTable").val(sChecked);
        });


    });
</script>

<style type="text/css">
    .x-large {
        width:90% !important;
    }
    
</style>

FoxConcept/Views/Recovery/_OptimizationSettingsGoalsList.cshtml
@using System.Collections.Concurrent
@model IEnumerable<FoxConcept.Models.ViewModels.Optimization.OptimizationGoal>
<table>
    <thead>
        <tr>
            <th width="2%">Consider</th>
            <th width="34%">Goal Name</th>
            <th width="66%">Importance</th>
        </tr>
    </thead>
    <tbody>
        @{var i = 0;}
        @foreach (var type in Model)
        {
            var isChecked = i != 0 ? null : "checked";
            <tr>
                <td>
                    <input data-val="true"  id="Goals_@{@i;}__.Selected" name="Goals[@i].Selected" type="checkbox" value="true"  @isChecked >
                    <input id="Goals_@{@i;}__.GoalTypeID" name="Goals[@i].GoalTypeID" type="hidden" value="@type.GoalTypeID" />
                    <input id="Goals_@{@i;}__.GoalTypeDescription" name="Goals[@i].GoalTypeDescription" type="hidden" value="@type.GoalTypeDescription" />
                </td>
                <td>@type.GoalTypeDescription</td>
                <td data-get="silder">
                    @if (type.Operators.Count() > 1)
                    {
                        <div style="margin-right: 10px; display: inline-block;"><span>Low</span></div>
                        <div class="slider" data-value="@type.Value" date-get="silderelement" id="slider-@type.GoalTypeID" style="width:50%;display: inline-table;"></div>
                        <div style="margin-left: 10px; margin-right: 10px; display: inline-block;"><span>High</span></div>
                        <div id="slider-result-@type.GoalTypeID" class="sliderresult" style="display: inline-table;"></div>
                        <input type="hidden" name="Goals[@i].Value" id="Goals_@{@i;}__.Value" value="@type.Value"/>
                    }
                    else
                    {
                        @type.Operators.ElementAt(0).Text;
                    }
                    @{ var j = 0;}
                    @foreach (var op in type.Operators)
                    {
                        <input type="hidden" name="Goals[@i].Operators[@j].Selected"/>
                        <input type="hidden" name="Goals[@i].Operators[@j].Text"/>
                        <input type="hidden" name="Goals[@i].Operators[@j].Value"/>
                        j++;
                    }

                    <span id="LimitInputBox-@type.GoalTypeID" class="hidden">
                        <input type="text" class="tiny" />%</span>
                </td>
                @*<td align="">
				<input class="tiny" type="text" id="PriorityInputBox-@type.GoalTypeID" />
			</td>*@

            </tr>
                    i++;
        }
    </tbody>
</table>

<script src="~/Scripts/JRange/jquery.range.js"></script>
<script>
    $("td[data-get='silder']").each(function (index, val) {
        var valu = $(val).find(".slider").attr("data-value");
        $(val).find(".slider").slider({
            range: "min",
            value: valu,
            min: 1,
            max: 100,
            //this gets a live reading of the value and prints it on the page
            slide: function (event, ui) {
                $(val).find(".sliderresult").text();
                $(val).find("input").val(ui.value);
            }
        });

    });

</script>