FoxConcept/Models/ViewModels/Certification/CertificationStatusViewModel.cs
namespace FoxConcept.Models
{
	using System;
	using System.Data.Entity;
	using System.Linq;
	using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations;
	using FoxConcept.Models.DALModels;

	public class CertificationStatusViewModel
	{
		public IEnumerable<DWH_Certification_Details_Main> AvailableCertifications { get; set; }
		public IEnumerable<DWH_User_Certification> UserCertificationData { get; set; }
		public CertificationStatusFilter FilterData { get; set; }

		public CertificationStatusViewModel()
		{
			AvailableCertifications = new List<DWH_Certification_Details_Main>();
			UserCertificationData = new List<DWH_User_Certification>();
			FilterData = new CertificationStatusFilter();
		}

		public class CertificationStatusFilter
		{
			public int? CertificationIDsFilter { get; set; }
			public DateTime? ExpirationStartDateFilter { get; set; }
			public DateTime? ExpirationEndDateFilter { get; set; }

			public CertificationStatusFilter()
			{
				CertificationIDsFilter = null;
				ExpirationEndDateFilter = null;
				ExpirationStartDateFilter = null;
			}
		}

	}
}

FoxConcept/Controllers/CertificationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FoxConcept.Models;
using FoxConcept.Models.DALModels;
using FoxConcept.Models.ViewModels.Shared;

namespace FoxConcept.Controllers
{
	public class CertificationController : Controller
	{
		
		[HttpGet]
		public ActionResult CertificationStatus()
		{
			CertificationStatusViewModel model = new CertificationStatusViewModel();
			using (var _context = new FoxModelContainer())
			{
				model.UserCertificationData = _context.DWH_User_Certifications.ToList();
				model.AvailableCertifications = getAvailableCertificationFIlter(_context);
			}

			return View("CertificationStatus", model);
		}

		private IEnumerable<DWH_Certification_Details_Main> getAvailableCertificationFIlter(FoxModelContainer _context)
		{
			var distinctCertsOfAllUsers = _context.DWH_User_Certifications.Select(c => c.Certification_ID).Distinct().ToList();
			var availableCerts = new List<DWH_Certification_Details_Main>();
			availableCerts.Add(new DWH_Certification_Details_Main { Cert_ID=-1, Cert_Name="" });
			availableCerts.AddRange(_context.DWH_Certification_Details_Main.Where(c => distinctCertsOfAllUsers.Contains(c.Cert_ID)).ToList());
			return availableCerts;
		}

		[HttpPost]
		public ActionResult CertificationStatus(CertificationStatusViewModel.CertificationStatusFilter FilterData)
        {
			CertificationStatusViewModel model = new CertificationStatusViewModel();
			using(var _context = new FoxModelContainer())
			{
				model.AvailableCertifications = getAvailableCertificationFIlter(_context);
				model.FilterData.CertificationIDsFilter = FilterData.CertificationIDsFilter;
				model.FilterData.ExpirationStartDateFilter = FilterData.ExpirationStartDateFilter;
				model.FilterData.ExpirationEndDateFilter = FilterData.ExpirationEndDateFilter;

				var CertificationIDsToFilter = FilterData.CertificationIDsFilter;
				model.UserCertificationData = _context.DWH_User_Certifications
					.Where(uc => uc.Certification_ID == CertificationIDsToFilter || CertificationIDsToFilter == -1).ToList();

				if (FilterData.ExpirationStartDateFilter.HasValue)
				{
					model.UserCertificationData.Where(uc=> uc.User_Certification_Final_Expiration_Date >= FilterData.ExpirationStartDateFilter);
				}

				if (FilterData.ExpirationEndDateFilter.HasValue)
				{
					model.UserCertificationData.Where(uc => uc.User_Certification_Final_Expiration_Date <= FilterData.ExpirationEndDateFilter);
				}

				
			}

			return View("CertificationStatus", model);
        }

		[HttpPost]
		public ActionResult ScheduleTraining(IEnumerable<string> UserCertifications)
		{
			var userCertificationData = UserCertifications.Select(s=> System.Web.Helpers.Json.Decode<DWH_User_Certification>(s)).ToList();
			AutomaticSchedulingSettingsViewModel model = new AutomaticSchedulingSettingsViewModel();
			using (var _context = new FoxModelContainer())
			{
				var userCertIDs = userCertificationData.Select(uc=>uc.Certification_ID).Distinct();
				var requiredCertifications = _context.DWH_Certification_Details_Main.Where(c => userCertIDs.Contains(c.Cert_ID)).ToList();
				var requiredTrainingForUsers = userCertificationData
					.Join(requiredCertifications, uc => uc.Certification_ID, c => c.Cert_ID, (uc, c) => new { 
						UserID  = uc.User_ID,
						CertificationID = uc.Certification_ID,
						CertificationStatus = uc.User_Certification_Status,
						ExpirationDate = uc.User_Certification_Final_Expiration_Date,
						MasterPlanID = ((new[] {1,8,9,10,13}).Contains(uc.User_Certification_Status.Value))? c.Cert_Acquiring_Master_Plan_ID : c.Cert_Renewal_Master_Plan_ID,
						MasterPlanName = ((new[] {1,8,9,10,13}).Contains(uc.User_Certification_Status.Value))? c.Cert_Acquiring_Master_Plan_Name : c.Cert_Renewal_Master_Plan_Name,
					}).ToList();

				var schedulingRequirements = requiredTrainingForUsers
					.Where(uc=>uc.MasterPlanID.HasValue)
					.GroupBy(t => new { MasterPlanID = t.MasterPlanID, MasterPlanName = t.MasterPlanName },
					(key, g) => new AutomaticSchedulingSettingsViewModel.AutomaticScheduleRequirement
					{
						MasterPlan = new MasterPlan {MasterPlanID=key.MasterPlanID.Value, MasterPlanName=key.MasterPlanName},
						RequiredEndDate = g.Max(uc=>uc.ExpirationDate),
						RequiredStartDate = g.Min(uc=>uc.ExpirationDate),
						RequiredQuantity = g.Count()
					}).ToList();

				model.SchedulingRequirements = schedulingRequirements.ToArray();
				
			}
			
			return RedirectToAction("Settings", "AutomaticScheduling", model);
		}

	}
}

FoxConcept/Views/Certification/CertificationStatus.cshtml
@model FoxConcept.Models.CertificationStatusViewModel

@{
	Layout = "~/Views/Shared/_FoxPageLayout.cshtml";
	ViewBag.Title = "Certification Status";
}


@helper getDueMonth(dynamic item)
	{
	var userCertificationItem = item.Value as FoxConcept.Models.DALModels.DWH_User_Certification;
	var expirationDate = userCertificationItem.User_Certification_Final_Expiration_Date;
	var dueMonth = expirationDate.HasValue ? expirationDate.Value.ToString("MM/yyy") : "";
	@Html.Raw(dueMonth);
}

@helper getCertificationStatusIcon(dynamic item)
	{
	var userCertificationItem = item.Value as FoxConcept.Models.DALModels.DWH_User_Certification;
	var certStatus = userCertificationItem.User_Certification_Status;
	var imageURL = string.Format("/Content/Images/CertificationStatuses/status{0}.png", certStatus);

	var certificationStatusStrings = new string[]{
		"None", 
		"Not acquired", 
		"Pending approval", 
		"Valid", 
		"Valid, validity has been extended due to equivalent certification",
		"Valid, validity has been shortened due to conditional certification", 
		"Expired", "Expired, due to conditional certification",
		"Revoked", 
		"In Registration",
		"Waiting for course",
		"Executing Course",
		"Not acquired",
		"Declined",
    };
	
	<img src="@imageURL" alt="@certificationStatusStrings[certStatus.Value]" title="@certificationStatusStrings[certStatus.Value]"/>
}

@helper getUserCertificationCheckbox(dynamic item)
{
	var userCertificationItem = item.Value as FoxConcept.Models.DALModels.DWH_User_Certification;
	<input class="UserCertCheckBox" 
			name="UserCertifications" 
			type="checkbox" 
			data-UserID="@item.User_ID"
			data-CertificationID="@item.Certification_ID" 
			value="@Json.Encode(userCertificationItem)" />
}

@helper getUserCertificationDataTable()
	{
		var dataSource = Model.UserCertificationData;
		WebGrid UserCertificationData = new WebGrid(source: dataSource, canPage: false);

		var tbl = UserCertificationData.GetHtml(tableStyle: "fixed-header", columns: UserCertificationData.Columns(
		UserCertificationData.Column(header: "{CheckBoxHeading}", style: "CheckboxColumn", format: @<text>@getUserCertificationCheckbox(item)</text>),
		UserCertificationData.Column(columnName: "User_Organizational_Unit_Name", header: "Organizational Unit", style: "User_Organizational_Unit_Name"),
		UserCertificationData.Column(columnName: "User_Name", header: "User Name", style: "User_Name"),
		UserCertificationData.Column(columnName: "Certification_Name", header: "Certification Name", style: "Certification_Name"),
		UserCertificationData.Column(columnName: "User_Certification_Status", header: "Status", style: "User_Certification_Status", format: @<text>@getCertificationStatusIcon(item)</text>),
		UserCertificationData.Column(columnName: "User_Certification_Final_Expiration_Date", header: "Due Month", style: "Due_Month", format: @<text>@getDueMonth(item)</text>)
		)).ToString().Replace("{CheckBoxHeading}", "<input type='checkbox' id='selectAllCheckBox' class='UserCertCheckBox'/>");
	
	@Html.Raw(tbl.ToString());
}


<div id="UserCertificationDataTable" class="container stretched-to-margin fixed-header-table-wrapper">
	<div class="TableHeader"><span>Certification Status</span></div>
	
	<div class="inline">
	@using (Html.BeginForm("CertificationStatus", "Certification", FormMethod.Post, null))
	{
	
		<div class="span8">
		<label for="CertificationIDsFilter" class="span2">Certification Name:</label>
		@Html.DropDownListFor(m => m.FilterData.CertificationIDsFilter, new SelectList(Model.AvailableCertifications.OrderBy(c=>c.Cert_Name), "Cert_ID", "Cert_Name"), new { Class = "x-large" })
		</div>
	
		<div class="span8">	
		<label for="ExpirationStartDateFilter" class="span2">Expiration Date From:</label>
		@Html.TextBoxFor(m => m.FilterData.ExpirationStartDateFilter, new { type = "date-picker", Class = "medium"})
		<label for="ExpirationEndDateFilter">To:</label>
		@Html.TextBoxFor(m => m.FilterData.ExpirationEndDateFilter, new { type = "date-picker", Class = "medium"})
		</div>
	 
		<input type="submit" class="small" value="Search" />
	
	}
	</div>

	@using (Html.BeginForm("Settings", "AutomaticScheduling", FormMethod.Post, new {style = "margin-top:90px; margin-bottom:20px;", Class = "stretched-to-margin", id = "CertStatusForm" }))
	{
	<div class="scrollable height90" >
		@getUserCertificationDataTable()
	</div>
	<div class="MultipleActionBar" data-toggler-element="UserCertCheckBox" id="UserCertificationDataTableActionBar">
		<a href="#" onclick="submitForm('ScheduleTraining')">Schedule Training</a>&nbsp;&nbsp;
		<a href="#" onclick="submitForm('AssignParticipants')">Assign to Scheduled Training</a>
	</div>
	 
	<input type="hidden" name="ActionType" id="ActionType" value="ScheduleTraining" />
	 
	}
</div>



@section Footer
{
	<script src="/Scripts/Certification/CertificationStatus.js" type="text/javascript"></script>
	<script type="text/javascript">
		function submitForm(actionType)
		{
			$("#ActionType").val(actionType);
			$("#CertStatusForm").submit();
		}
	</script>
	
}