FoxConcept/Models/ViewModels/Shared/Activity.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace FoxConcept.Models.ViewModels.Shared
{
	public class Activity
	{
		public int ActivityID { get; set; }
		public string ActivityName { get; set; }
		public int ActivityDuration { get; set; }

		public List<Prerequisite> ActivityPrerequisites { get; set; }
		public List<ParticipantRequirement> ActivityParticipantRequirements  { get; set; }
		public List<ResourceRequirement> ActivityResourceRequirements { get; set; }



	}

	public class Prerequisite
	{
		public int PrerequisiteActivityID { get; set; }
		public string PrerequisiteActivityName {get;set;}
		public int? PrerequisiteCompletionsMaxDays { get; set; }
		public int? PrerequisiteCompletionsMinDays { get; set; }

	}

	
}

FoxConcept/Models/ViewModels/Shared/FoxEvent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace FoxConcept.Models.ViewModels.Shared
{
	public class FoxEvent
	{
		public int ActivityID { get; set; }
		public DateTime StartDate { get; set; }
		public DateTime EndDate { get; set; }
		public List<ResourceAllocation> AllocatedResources { get; set; }
		public int DurationInMinutes
		{
			get { return (int)(EndDate - StartDate).TotalMinutes; }
		}

	}

	public class ResourceAllocation
	{
		public int AllocationID { get; set; }
		public DateTime StartTime { get; set; }
		public DateTime EndTime { get; set; }
		public int ResourceID { get; set; }
		public int ResourceTypeID { get; set; }
		public string ResourceTypeName { get; set; }
		public int DurationInMinutes
		{
			get { return (int)(EndTime - StartTime).TotalMinutes; }
		}

		public int OriginalRequirementID { get; set; }
		public int Origin { get; set; }

	}
}

FoxConcept/Models/ViewModels/Shared/FoxUser.cs
namespace FoxConcept.Models.ViewModels.Shared
{
    using System;
    using System.Collections.Generic;
    
    public class FoxUser
    {
        public int UserID { get; set; }
        public string UserFirstName { get; set; }
        public string UserLastName { get; set; }
        public string UserLoginName { get; set; }
        public string UserExternalID { get; set; }
        public string UserRank { get; set; }
        public Nullable<System.DateTime> UserCreationDate { get; set; }
        public Nullable<bool> UserAllowEmailNotifications { get; set; }
        public int User_OrganizationalUnitID { get; set; }
        public string User_OrganizationalUnitName { get; set; }
        public string User_OrganizationalUnitExternalID { get; set; }
        public Nullable<int> User_LocationID { get; set; }
        public Nullable<int> User_CustomerID { get; set; }
        public string User_CustomerName { get; set; }
    }
}

FoxConcept/Models/ViewModels/Shared/MasterPlan.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace FoxConcept.Models.ViewModels.Shared
{
	public class MasterPlan
	{
		public int MasterPlanID { get; set; }
		public string MasterPlanName { get; set; }
		public List<Activity> ActivitiesToSchedule { get; set; }
	    public int SelectedMasterPlan { get; set; }
	    public string RequiredQuatity { get; set; }
	}
}

FoxConcept/Models/ViewModels/Shared/Resource.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace FoxConcept.Models.ViewModels.Shared
{
	public class Resource
	{
		public int ResourceID { get; set; }
		public String ResourceName { get; set; }
		public int ResourceTypeID { get; set; }
		public string ResourceTypeName { get; set; }
		public int ResourceLocationID { get; set; }
		public List<ResourceProperties> ResourceProperties { get; set; }
		public List<ResourceCertifications> ResourceCertifications { get; set; }
		public List<Event> ResourceUnavailability { get; set; }


	}

	public class ResourceProperties
	{
		public int? PropertyID { get; set; }
		public string PropertyName { get; set; }
		public int? PropertyTypeID { get; set; }
		public string PropertyTypeName { get; set; }
		public int? IsMultipleChoice { get; set; }
		public string Value { get; set; }
		public string[] SelectedOptionIDs { get; set; }
	}

	public class ResourceCertifications
	{
		public int CertificationID { get; set; }
		public string CretificationName { get; set; }
		public string ExpirationDate { get; set; }
	}
}

FoxConcept/Models/ViewModels/Shared/ResourceRequirement.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace FoxConcept.Models.ViewModels.Shared
{
	public class ResourceRequirement
	{
		public int RequirementID { get; set; }
		public string RequirementResourceTypeName { get; set; }
		public int RequirementResourceTypeID { get; set; }
		public int RequirementStartTimeDelta { get; set; }
		public int RequirementEndTimeDelta { get; set; }

		public List<RequirementProperties> RequirementProperties { get; set; }
		public int[] CertificationRequirementIDs { get; set; }


	}


	public class RequirementProperties
	{
		public int PropertyID { get; set; }
		public string PropertyName { get; set; }
		public int PropertyTypeID { get; set; }
		public string PropertyTypeName { get; set; }
		public int OperatorID { get; set; }
		public int? IsMultipleChoice { get; set; }
		public string Value { get; set; }
		public string MinValue { get; set; }
		public string MaxValue { get; set; }
		public string[] SelectedOptionIDs { get; set; }
	}

}

FoxConcept/Models/ViewModels/Shared/ResourceType.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace FoxConcept.Models.ViewModels.Shared
{
	public class ResourceType
	{
		public int TypeID { get; set; }
		public string TypeName { get; set; }

		public ResourceType() { }

		public ResourceType(int i_ResTypeID, string i_ResName)
		{
			TypeID = i_ResTypeID;
			TypeName = i_ResName;
		}

		public bool isSelected { get; set; }


		public class ResourceTypeComparer : IEqualityComparer<ResourceType>
		{
			public bool Equals(ResourceType x, ResourceType y)
			{
				return x.TypeID == y.TypeID;
			}

			public int GetHashCode(ResourceType obj)
			{
				return obj.TypeID;
			}
		}
	}
}

FoxConcept/Models/ViewModels/Shared/TrainingProgram.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace FoxConcept.Models.ViewModels.Shared
{
	public class TrainingProgram
	{
		public int TrainingProgramID { get; set; }
		public int? MasterPlanID { get; set; }
		public string MasterPlanName { get; set; }
		public string TrainingProgramPlanName { get; set; }
		public DateTime? StartDate { get; set; }
		public DateTime? EndDate { get; set; }
		public List<TrainingRequest> AnsweredRequests { get; set; }
		public List<FoxEvent> Events { get; set; }
		public bool isScheduled { get; set; }
		public int OriginalRequestID { get; set; }

		public long MasterPlanCost { get; set; }
		public long MasterPlanRevenue { get; set; }
	}
}

FoxConcept/Models/ViewModels/Shared/UserUnavalability.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace FoxConcept.Models.ViewModels.Shared
{
	public class UserUnavalability
	{
		public int UserID { get; set; }
		public string UserName { get; set; }
		public List<Event> UserUnavailability { get; set; }
	}
}

FoxConcept/Controllers/CostSettingsController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.Migrations;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FoxConcept.Models;
using FoxConcept.Models.DALModels;
using FoxConcept.Models.ViewModels.CostSettings;

namespace FoxConcept.Controllers
{
    public class CostSettingsController : Controller
    {
        //
        // GET: /CostSettings/

        FoxConceptEntities _FoxConceptDB = new FoxConceptEntities();
        FoxModelContainer _FoxDB = new FoxModelContainer();

        protected override void Dispose(bool disposing)
        {
            _FoxConceptDB.Dispose();
            _FoxDB.Dispose();
            base.Dispose(disposing);
        }

        public ActionResult GetCosts(int? EntityType)
        {
            if (EntityType != null)
            {
                switch ((eEntityType)EntityType)
                {
                    case eEntityType.Activity:
                        {
                            return RedirectToAction("GetActivitiesCosts");
                            break;
                        }
                    case eEntityType.HumanResource:
                        {
                            return RedirectToAction("GetHumanResourcesCosts");
                            break;
                        }
                    case eEntityType.PhysicalResource:
                        {
                            return RedirectToAction("GetPhysicalResourcesCosts");
                            break;
                        }
                    case eEntityType.Participant:
                        {
                            return RedirectToAction("GetParticipantsCosts");
                            break;
                        }
                }
            }
            return View();
        }

        public ActionResult GetActivitiesCosts()
        {
            return View();
        }

        public ActionResult GetHumanResourcesCosts()
        {
            CostSettingsViewModel model = new CostSettingsViewModel();
            model.CostSettingViewModels =
                _FoxConceptDB.EntitiesCostSettings.Where(c => c.EntityType == ((int)eEntityType.HumanResource)).AsEnumerable()
                             .Select(c => new CostSettingViewModel
                                 {
                                     ID = c.ID,
                                     StateType = (eStateType)c.StateType,
                                     EntityType = eEntityType.HumanResource,
                                     Name = c.Name,
                                     TargetGroupType = (eTargetGroupType)c.TargetGroupType,
                                     ConsiderInOptimization = (bool)c.ConsiderInOptimization,
                                     Cost = (decimal)c.Cost,
                                     CostPer = (eCostPer)c.CostPer,
                                     CostType = (eCostType)c.CostType,
                                     EntityTypeName = c.EntityTypeName,
                                     EntityTypeID = c.EntityTypeID,
                                     Comments = c.Comments
                                 }).ToList();

            return View(model);
        }

        public ActionResult GetPhysicalResourcesCosts()
        {
            CostSettingsViewModel model = new CostSettingsViewModel();
            model.CostSettingViewModels =
                _FoxConceptDB.EntitiesCostSettings.Where(c => c.EntityType == ((int)eEntityType.PhysicalResource)).AsEnumerable()
                             .Select(c => new CostSettingViewModel
                             {
                                 ID = c.ID,
                                 StateType = (eStateType)c.StateType,
                                 EntityType = eEntityType.HumanResource,
                                 Name = c.Name,
                                 TargetGroupType = (eTargetGroupType)c.TargetGroupType,
                                 ConsiderInOptimization = (bool)c.ConsiderInOptimization,
                                 Cost = (decimal)c.Cost,
                                 CostPer = (eCostPer)c.CostPer,
                                 CostType = (eCostType)c.CostType,
                                 EntityTypeName = c.EntityTypeName,
                                 EntityTypeID = c.EntityTypeID,
                                 Comments = c.Comments
                             }).ToList();

            return View(model);
        }

        public ActionResult GetParticipantsCosts()
        {
            CostSettingsViewModel model = new CostSettingsViewModel();
            model.CostSettingViewModels =
                _FoxConceptDB.EntitiesCostSettings.Where(c => c.EntityType == ((int)eEntityType.Participant)).AsEnumerable()
                             .Select(c => new CostSettingViewModel
                             {
                                 ID = c.ID,
                                 StateType = (eStateType)c.StateType,
                                 EntityType = eEntityType.HumanResource,
                                 Name = c.Name,
                                 TargetGroupType = (eTargetGroupType) c.TargetGroupType,
                                 ConsiderInOptimization = (bool)c.ConsiderInOptimization,
                                 Cost = (decimal)c.Cost,
                                 CostPer = (eCostPer)c.CostPer,
                                 CostType = (eCostType)c.CostType,
                                 EntityTypeName = c.EntityTypeName,
                                 LocationID = (int)c.LocationID,
                                 EntityTypeID = c.EntityTypeID,
                                 Comments = c.Comments
                             }).ToList();

            return View(model);
        }

        public ActionResult GetCostTypes()
        {
            IEnumerable<CostTypeViewModel> model = _FoxConceptDB.CostTypesSettings.Select(c => new CostTypeViewModel()
                {
                    ID = c.ID,
                    Name = c.Name,
                    CostType = (eCostType)c.CostType,
                    Cost = c.Cost,
                    LocationID = (int)c.LocationID,
                    LocationName = c.LocationName,
                    CostPer = (eCostPer)c.CostPer
                }).ToList();

            return View(model);
        }

        #region Humanresource
        public ActionResult AddHumanResourceCost()
        {
            CostSettingViewModel model = new CostSettingViewModel();
            model.EntityType = eEntityType.HumanResource;
            model.EntityTypes =
                _FoxDB.DWH_ResourcesBasicData.Where(r => r.ResourceType == 2).Select(r => new EntityType()
                          {
                              ID = r.ResourceMetaDataTypeID,
                              Name = r.ResourceMetaDataTypeName
                          }).Distinct().OrderBy(r => r.Name).ToList();

            model.Locations = GetLocations();



            return View(model);
        }

        private List<EntityType> GetLocations()
        {
            return _FoxDB.BKS_DWH_Locations.Select(l => new EntityType()
            {
                ID = l.LocationID,
                Name = l.LocationName
            }).ToList();
        }

        public ActionResult EditHumanResourceCost(int ID)
        {
            CostSettingViewModel model = new CostSettingViewModel();
            model.EntityType = eEntityType.HumanResource;
            model.EntityTypes =
                _FoxDB.DWH_ResourcesBasicData.Where(r => r.ResourceType == 2).Select(r => new EntityType()
                {
                    ID = r.ResourceMetaDataTypeID,
                    Name = r.ResourceMetaDataTypeName
                }).Distinct().OrderBy(r => r.Name).ToList();

            model.Locations = GetLocations();

            var _entity = _FoxConceptDB.EntitiesCostSettings.FirstOrDefault(e => e.ID == ID);

            model.ID = _entity.ID;
            model.StateType = (eStateType)_entity.StateType;
            model.Name = _entity.Name;
            model.TargetGroupType = (eTargetGroupType)_entity.TargetGroupType;
            model.Cost = (decimal)_entity.Cost;
            model.Comments = _entity.Comments;
            model.ConsiderInOptimization = (bool)_entity.ConsiderInOptimization;
            model.CostPer = (eCostPer)_entity.CostPer;
            model.CostType = (eCostType)_entity.CostType;
            model.EntityTypeID = _entity.EntityTypeID;
            model.EntityTypeName = _entity.EntityTypeName;
            model.LocationID = (int)_entity.LocationID;
            model.LocationName = _entity.LocationName;

            return View(model);
        }

        [HttpPost]
        public ActionResult EditHumanResourceCost(CostSettingViewModel model)
        {
            var _entity = _FoxConceptDB.EntitiesCostSettings.FirstOrDefault(e => e.ID == model.ID);

            _entity.EntityType = (int)eEntityType.HumanResource;
            _entity.EntityTypeID = model.EntityTypeID;

            _entity.EntityTypeName =
                _FoxDB.DWH_ResourcesBasicData.Where(r => r.ResourceMetaDataTypeID == model.EntityTypeID)
                      .FirstOrDefault()
                      .ResourceMetaDataTypeName;
            _entity.StateType = (int)model.StateType;
            _entity.TargetGroupType = (int)model.TargetGroupType;
            _entity.Name = model.Name;
            _entity.Cost = model.Cost;
            _entity.CostType = (int)model.CostType;
            _entity.CostPer = (int)model.CostPer;
            _entity.ConsiderInOptimization = model.ConsiderInOptimization;
            _entity.Comments = model.Comments;
            _entity.LocationID = model.LocationID;
            _entity.LocationName = _FoxDB.BKS_DWH_Locations.FirstOrDefault(l => l.LocationID == model.LocationID).LocationName;

FoxConcept/Views/Shared/_CostSettingsLayout.cshtml
@using FoxConcept.Models.ViewModels.CostSettings
@{
    ViewBag.Title = ViewBag.Title;
    Layout = "~/Views/Shared/_FoxPageLayout.cshtml";
}
@section Header
{
    <link href="/Content/dropit.css" rel="stylesheet" type="text/css" />
}

<div id="CostSettingsTable" class="container ">
    <div class="TableHeader">
        <span>Costs Settings</span>
        <ul class="menu dropit pull-right">
            <li>
                @RenderSection("AddButton", false)
            </li>
        </ul>
       
    </div>
</div>

<div class="LeftPanel">
    <table class="listTable">
        <thead>
            <tr>
                <th width="2%">&nbsp;</th>
                <th width="98%">Category</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>&nbsp;</td>
                <td>@Html.NavigationTab(@Url.Action("GetParticipantsCosts","CostSettings"),"Participant Costs", null)</td>
            </tr>
            <tr>
                <td>&nbsp;</td>
                <td>@Html.NavigationTab(@Url.Action("GetHumanResourcesCosts","CostSettings"),"Human Resources Costs", null)</td>
            </tr>
            <tr>
                <td>&nbsp;</td>
                <td>@Html.NavigationTab(@Url.Action("GetPhysicalResourcesCosts","CostSettings"),"Physical Resources Costs", null)</td>
            </tr>
            <tr>
                <td>&nbsp;</td>
                <td>@Html.NavigationTab(@Url.Action("GetCostTypes","CostSettings"),"Additional Costs", null)</td>
            </tr>
            @*<tr>
                <td>&nbsp;</td>
                <td>@Html.ActionLink("Scheduling Rules Types", "GetCosts", "CostSettings", new { @EntityType = eEntityType.Activity }, null)</td>
            </tr>*@
        </tbody>
    </table>
</div>
<div class="RightPanel">
    @RenderBody()
</div>
@RenderSection("Footer", false)

FoxConcept/Views/Shared/_FoxFormLayout.cshtml
<!DOCTYPE html>
<html>
<head>
	<title>@ViewBag.Title</title>
	<link href="/Content/Fox.css" rel="stylesheet" type="text/css" />
	<link href="/Content/themes/Aristo/Aristo.css" rel="stylesheet" type="text/css" />
	<link href="/Content/timeline.css" rel="stylesheet" type="text/css" />
	<link href="/Content/timeline-theme.css" rel="stylesheet" type="text/css" />
	<link href="/Scripts/jqTips/jquery.qtip.min.css" rel="stylesheet" type="text/css" />

	<script src="/Scripts/Common/jquery-1.10.2.min.js" type="text/javascript"></script>
	<script src="/Scripts/Common/jquery-ui-1.10.3.min.js" type="text/javascript"></script>
	<script src="/Scripts/Common/Common.js" type="text/javascript"></script>
	<script src="/Scripts/Common/jquery.stickytableheaders.min.js" type="text/javascript"></script>
	<script src="/Scripts/Common/timeline.js" type="text/javascript"></script>
	<script src="/Scripts/Common/google.jsapi.js" type="text/javascript"></script>
	<script src="/Scripts/Common/google.visualization.js" type="text/javascript"></script>
	<script src="/Scripts/jqTips/jquery.qtip.min.js" type="text/javascript"></script>
	<script src="/Scripts/Common/jquery.formatCurrency-1.4.0.js" type="text/javascript"></script>
    
    @RenderSection("scripts",false)

</head>
<body>
	<div class="FormHeader">
	<img src="/Content/Images/ic_BKS.gif" alt="@ViewBag.Title" />
		@RenderSection("FormHeader", false)
	</div>
	
	<div class="stretched-to-margin FormBody">
	@RenderBody()
	</div>

	<div class="FormFooter">
		@RenderSection("FormFooter", false)
	</div>
</body>
</html>

FoxConcept/Views/Shared/_FoxPageLayout.cshtml
<!DOCTYPE html>
<html>
<head>
	<title>@ViewBag.Title</title>
	<link href="/Content/Fox.css" rel="stylesheet" type="text/css" />
	<link href="/Content/themes/Aristo/Aristo.css" rel="stylesheet" type="text/css" />
	<link href="/Content/timeline.css" rel="stylesheet" type="text/css" />
	<link href="/Content/timeline-theme.css" rel="stylesheet" type="text/css" />
	<link href="/Scripts/jqTips/jquery.qtip.min.css" rel="stylesheet" type="text/css" />

	<script src="/Scripts/Common/jquery-2.0.2.min.js" type="text/javascript"></script>
	<script src="/Scripts/Common/jquery-ui-1.10.3.min.js" type="text/javascript"></script>
	<script src="/Scripts/Common/Common.js" type="text/javascript"></script>
	<script src="/Scripts/Common/jquery.stickytableheaders.min.js" type="text/javascript"></script>
	<script src="/Scripts/Common/timeline.js" type="text/javascript"></script>
	<script src="/Scripts/Common/google.jsapi.js" type="text/javascript"></script>
	<script src="/Scripts/Common/google.visualization.js" type="text/javascript"></script>
	<script src="/Scripts/jqTips/jquery.qtip.min.js" type="text/javascript"></script>
	<script src="/Scripts/Common/jquery.formatCurrency-1.4.0.js" type="text/javascript"></script>
	
	@RenderSection("Header", false)

</head>
<body>

	<div class="stretched-to-margin">
	@RenderBody()
	</div>

	@RenderSection("Footer", false)
</body>
</html>

FoxConcept/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
	
	<script src="/Scripts/jquery-2.0.2.min.js" type="text/javascript"></script>
	<script src="/Scripts/jquery-ui-1.10.3.min.js" type="text/javascript"></script>
	<script src="../../Scripts/Common/jquery.floatThead.min.js" type="text/javascript"></script>
</head>

<body>
    @RenderBody()
</body>
</html>