FoxConcept/Models/DALModels/BiddingRequest.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoxConcept.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BiddingRequest
    {
        public int ID { get; set; }
        public int InstructorID { get; set; }
        public int BiddingRuleID { get; set; }
        public int BiddingPeriodID { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public int Priority { get; set; }
        public string Comments { get; set; }
        public string InstructorName { get; set; }
        public int Status { get; set; }
    
        public virtual BiddingPeriod BiddingPeriod { get; set; }
        public virtual BiddingRule BiddingRule { get; set; }
    }
}

FoxConcept/Models/ViewModels/BiddingRequests/BiddingRequestViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using FoxConcept.Models.ViewModels.CostSettings;

namespace FoxConcept.Models.ViewModels.BiddingRequests
{

    public class BiddingRequestsViewMode
    {
        public int InstractorID { get; set; }
        public Instructor Instructor { get; set; }
        public IEnumerable<BiddingRequestViewModel> BiddingRequests { get; set; }
        public IEnumerable<BiddingRule> BiddingRules { get; set; }

        void Foo(){} 

        public BiddingRequestsViewMode()
        {
            BiddingRequests = new List<BiddingRequestViewModel>();
            Instructor = new Instructor();
            BiddingRules = new List<BiddingRule>();
        }
    }

    public class BiddingRequestViewModel
    {
        public int ID { get; set; }

        [Display(Name = "Instructor")]
        public int InstructorID { get; set; }

        [Display(Name = "Instructor")]
        public string InstructorName { get; set; }

        [Display(Name = "Bidding Rule")]
        public int BiddingRuleID { get; set; }

        [Display(Name = "Bidding Type")]
        public BiddingRule BiddingRule { get; set; }

        [Display(Name = "Bidding Period")]
        public int BiddingPeriodID { get; set; }

        [Display(Name = "Bidding Period")]
        public BiddingPeriod BiddingPeriod { get; set; }

        public IEnumerable<BiddingPeriod> BiddingPeriods { get; set; }

        [Display(Name = "Start Date")]
        public DateTime StartDate { get; set; }

        [Display(Name = "End Date")]
        public DateTime? EndDate { get; set; }

        [Display(Name = "Priority")]
        public int Priority { get; set; }

        [Display(Name = "Requested days left")]
        public int RequestsLeft { get; set; }

        public string Comments { get; set; }

        public BiddingRequest.eStatusRequest Status { get; set; }

        public BiddingRequestViewModel()
        {
            BiddingPeriods = new List<BiddingPeriod>();
        }

    }

    public class Instructor
    {
        public int ID { get; set; }

        public string Name { get; set; }

        public int EntityTypeID { get; set; }
    }

    public class BiddingManagementViewModel
    {
        //Filters
        [Display(Name = "Instructor")]
        public List<EntityType> Instructors { get; set; }
        [Display(Name = "Instructor")]
        public int InstructorID { get; set; }

        [Display(Name = "Bidding Periods")]
        public List<EntityType> BiddingPeriods { get; set; }
        [Display(Name = "Bidding Period")]
        public int BiddingPeriodID { get; set; }

        public IEnumerable<BiddingRequestViewModel> BiddingRequests { get; set; }

        public BiddingManagementViewModel()
        {
            BiddingRequests = new List<BiddingRequestViewModel>();
            this.BiddingPeriods = new List<EntityType>();
            BiddingPeriods.Add(new EntityType()
                {
                    ID = -1,
                    Name = "Select a Value"
                });

            this.Instructors = new List<EntityType>();
            this.Instructors.Add(new EntityType()
                {
                    ID = -1,
                    Name = "Select a Value"
                });
        }
    }
}

FoxConcept/Controllers/BiddingRequestsController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.Migrations;
using System.Data.Entity.Validation;
using System.Data.Objects.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using FoxConcept.Models;
using FoxConcept.Models.DALModels;
using FoxConcept.Models.ViewModels.BiddingRequests;
using FoxConcept.Models.ViewModels.CostSettings;

namespace FoxConcept.Controllers
{
    public class BiddingRequestsController : Controller
    {
        FoxConceptEntities _FoxConceptDB = new FoxConceptEntities();
        FoxModelContainer _FoxDB = new FoxModelContainer();

        protected override void Dispose(bool disposing)
        {
            _FoxConceptDB.Dispose();
            _FoxDB.Dispose();
            base.Dispose(disposing);
        }

        //
        // GET: /BiddingRequests/

        public ActionResult Index(int InstructorID)
        {
            BiddingRequestsViewMode model = new BiddingRequestsViewMode();
            model.InstractorID = InstructorID;

            // Get Instrctor information
            model.Instructor =
                _FoxDB.DWH_ResourcesBasicData.Where(i => i.ResourceUserID == InstructorID).AsEnumerable().Select(i => new Instructor()
                    {
                        ID = (int)i.ResourceUserID,
                        Name = i.ResourceName,
                        EntityTypeID = i.ResourceMetaDataTypeID
                    }).FirstOrDefault();

            if (model.Instructor != null)
            {
                model.BiddingRules =
                _FoxConceptDB.BiddingRules.Where(r => r.EntityTypeID == model.Instructor.EntityTypeID).ToList();
            }


            model.BiddingRequests =
                _FoxConceptDB.BiddingRequests.Include("BiddingPeriod")
                             .Include("BiddingRule")
                             .AsEnumerable()
                             .Select(b => new BiddingRequestViewModel()
                                 {
                                     ID = b.ID,
                                     BiddingPeriod = b.BiddingPeriod,
                                     BiddingRule = b.BiddingRule,
                                     BiddingPeriodID = b.BiddingPeriodID,
                                     BiddingRuleID = b.BiddingRuleID,
                                     StartDate = b.StartDate,
                                     EndDate = b.EndDate.HasValue ? b.EndDate : null,
                                     InstructorID = b.InstructorID,
                                     InstructorName = b.InstructorName,
                                     Comments = b.Comments,
                                     Status = b.StatusEnum,
                                     Priority = b.Priority
                                 }).ToList();

            return View(model);
        }

        [HttpGet]
        public ActionResult AddBiddingRequest(int InstructorID, int biddingRule)
        {
            BiddingRequestViewModel model = new BiddingRequestViewModel();

            model.BiddingRule = _FoxConceptDB.BiddingRules.FirstOrDefault(r => r.ID == biddingRule);

            model.RequestsLeft = model.BiddingRule.DaysPerInstructor - _FoxConceptDB.BiddingRequests.Where(
                            r =>
                            r.BiddingRuleID == biddingRule && r.InstructorID == InstructorID).AsEnumerable().Select(r => new
                            {
                                Days =
                                                                                                   r.EndDate
                                                                                                    .HasValue
                                                                                                       ? Convert
                                                                                                             .ToInt16
                                                                                                             (((
                                                                                                               DateTime
                                                                                                               )
                                                                                                               r
                                                                                                                   .EndDate -
                                                                                                               (
                                                                                                               DateTime
                                                                                                               )
                                                                                                               r
                                                                                                                   .StartDate)
                                                                                                                  .TotalDays)
                                                                                                       : 1
                            }).Sum(r => r.Days);

            model.InstructorID = InstructorID;
            model.BiddingRuleID = biddingRule;

            model.StartDate = DateTime.Now;
            model.EndDate = DateTime.Now;
            model.Priority = 1;

            model.BiddingPeriods = model.BiddingRule.GetActiveBiddingPeriods();


            return View(model);
        }

        [HttpPost]
        public ActionResult AddBiddingRequest(BiddingRequestViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    int requested =
                        _FoxConceptDB.BiddingRequests.Where(
                            r =>
                            r.BiddingRuleID == model.BiddingRuleID && r.InstructorID == model.InstructorID &&
                            r.BiddingPeriodID == model.BiddingPeriodID).AsEnumerable().Select(r => new
                                {
                                    Days =
                                                                                                       r.EndDate
                                                                                                        .HasValue
                                                                                                           ? Convert
                                                                                                                 .ToInt16
                                                                                                                 (((
                                                                                                                   DateTime
                                                                                                                   )
                                                                                                                   r
                                                                                                                       .EndDate -
                                                                                                                   (
                                                                                                                   DateTime
                                                                                                                   )
                                                                                                                   r
                                                                                                                       .StartDate)
                                                                                                                      .TotalDays)
                                                                                                           : 1
                                }).Sum(r => r.Days);


                    model.BiddingRule = _FoxConceptDB.BiddingRules.FirstOrDefault(r => r.ID == model.BiddingRuleID);
                    if (model.BiddingRule.DaysPerInstructor < requested)
                    {
                        ModelState.AddModelError("Requestleft", "You exceeded the number of requests for this pertiod");
                        model.BiddingPeriods = model.BiddingRule.GetActiveBiddingPeriods();
                        return View(model);
                    }

                    BiddingRequest _request = new BiddingRequest();
                    _request.InstructorID = model.InstructorID;
                    _request.BiddingRuleID = model.BiddingRuleID;
                    _request.BiddingPeriodID = model.BiddingPeriodID;
                    _request.StartDate = model.StartDate;
                    _request.StatusEnum = BiddingRequest.eStatusRequest.New;
                    _request.InstructorName =
                        _FoxDB.DWH_ResourcesBasicData.FirstOrDefault(r => r.ResourceUserID == _request.InstructorID)
                              .ResourceName;
                    if (model.EndDate.HasValue)
                    {
                        _request.EndDate = model.EndDate;
                    }
                    else
                    {
                        _request.EndDate = _request.StartDate;
                    }

                    _request.Priority = model.Priority;
                    _request.Comments = model.Comments;

                    _FoxConceptDB.BiddingRequests.Add(_request);

                    int results = _FoxConceptDB.SaveChanges();

FoxConcept/Views/BiddingRequests/AddBiddingRequest.cshtml
@model FoxConcept.Models.ViewModels.BiddingRequests.BiddingRequestViewModel
@{
    ViewBag.Title = "Add Bidding Request - " + Model.BiddingRule.Name;
    Layout = "~/Views/Shared/_FoxFormLayout.cshtml";
}
@section scripts
{
    <script src="@Url.Content("~/Scripts/jquery.validate.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/FormAjax.js")" type="text/javascript"></script>
}
@section FormHeader
{
    <span>@ViewBag.Title</span>
    @*<link href="/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />*@
    <link href="/Content/datepicker3.css" rel="stylesheet" type="text/css" />
}

<div class="container">
    @using (Html.BeginForm("AddBiddingRequest", "BiddingRequests", FormMethod.Post, null))
    {
        
        <div>@Html.ValidationMessage("Requestleft")</div>
        <fieldset>
            <legend>Request Details</legend>
            @Html.HiddenFor(m => m.InstructorID)
            @Html.HiddenFor(m => m.BiddingRuleID)
            <div class="alert-block">Requests left: @Model.RequestsLeft</div>
            <div class="span10">
                @Html.LabelFor(m => m.BiddingPeriodID, new { @class = "span2" })
                @Html.DropDownListFor(m => m.BiddingPeriodID, new SelectList(Model.BiddingPeriods, "ID", "BiddingPeriodString"), new { @class = "x-large" })
                @Html.ValidationMessageFor(m => m.BiddingPeriodID)
            </div>

            <div class="span10">
                @Html.LabelFor(m => m.StartDate, new { @class = "span2" })
                @Html.TextBoxFor(m => m.StartDate, new { @class = "x-large datepicker", @Value = (Model.StartDate).ToString("MM/dd/yyyy") })
                @Html.ValidationMessageFor(m => m.StartDate)
            </div>

            <div class="span10">
                @Html.LabelFor(m => m.EndDate, new { @class = "span2" })
                @Html.TextBoxFor(m => m.EndDate, new { @class = "x-large datepicker", @Value = ((DateTime)Model.EndDate).ToString("MM/dd/yyyy") })
                @Html.ValidationMessageFor(m => m.EndDate)

            </div>

            <div class="span10">
                @Html.LabelFor(m => m.Priority, new { @class = "span2" })
                @Html.TextBoxFor(m => m.Priority, new { @class = "x-large " })
                @Html.ValidationMessageFor(m => m.Priority)
            </div>
            <div class="span10">
                @Html.LabelFor(m => m.Comments, new { @class = "span2" })
                @Html.TextAreaFor(m => m.Comments, new { @class = "x-large " })
                @Html.ValidationMessageFor(m => m.Comments)
            </div>
        </fieldset>
    }

</div>
@section FormFooter
{
    <a href="javascript:window.close()">
        <img alt="Close" src="/Content/Images/FoxClose.gif" />
        Close</a>
    <a href="#" id="FormSubmit">Save</a>
    <div id="progressSpan" class="Progress" data-success="@Url.Content("~/Content/Succeeded.gif")" style="display: none;">
        <span id="progressText"></span>
        <img id="progressImg" alt="" src="@Url.Content("~/Content/InProcess.gif")">
    </div>
    @*<a href="#"  onclick="document.forms[0].submit()">Save</a>*@


}

<script type="text/javascript">
    $(function () {
        $('.datepicker').datepicker({
            format: "dd/mm/yyyy",
            todayBtn: true,
            clearBtn: true
        });
    });
</script>

FoxConcept/Views/BiddingRequests/ApproveBiddingRequest.cshtml
@model FoxConcept.Models.ViewModels.BiddingRequests.BiddingRequestViewModel
@{
    ViewBag.Title = "Review Request";
    Layout = "~/Views/Shared/_FoxFormLayout.cshtml";
}

@section scripts
{
    <script src="@Url.Content("~/Scripts/jquery.validate.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/FormAjax.js")" type="text/javascript"></script>
}
@section FormHeader
{
    <span>@ViewBag.Title</span>
    @*<link href="/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />*@
    <link href="/Content/datepicker3.css" rel="stylesheet" type="text/css" />
}



<div class="container">
    @using (Html.BeginForm("ApproveBiddingRequest", "BiddingRequests", FormMethod.Post, null))
    {
        <fieldset>
            @*<legend>@Model.InstructorName Bidding request</legend>
            @Html.HiddenFor(m => m.ID)*@
            <legend>Request Details</legend>

            <div class="span10">
                @Html.LabelFor(m => m.InstructorName, new { @class = "formlabel span2" })
                <p class="formParag">@Model.InstructorName</p>
            </div>
            <div class="span10">
                @Html.LabelFor(m => m.BiddingPeriodID, new { @class = "formlabel span2" })
                <p class="formParag">@Model.BiddingPeriod.BiddingPeriodString</p>
            </div>
            <div class="span10">
                @Html.LabelFor(m => m.BiddingRule, new { @class = "formlabel span2" })
                <p class="formParag">@Model.BiddingRule.Name</p>
            </div>
            <div class="span10">
                @Html.LabelFor(m => m.Priority, new { @class = "formlabel span2" })
                <p class="formParag">@Model.Priority</p>
            </div>
            <div class="span10">
                @Html.LabelFor(m => m.StartDate, new { @class = "formlabel span2" })
                <p class="formParag">@Model.StartDate.ToString("MM/dd/yyyy")</p>
            </div>
            <div class="span10">
                @Html.LabelFor(m => m.EndDate, new { @class = "formlabel span2" })
                <p class="formParag">
                    @{
                        var enddate = Model.EndDate != null ? ((DateTime)Model.EndDate).ToString("MM/dd/yyyy") : String.Empty;
                    }@enddate
                </p>
            </div>
            <div class="span10">
                @Html.LabelFor(m => m.RequestsLeft, new { @class = "formlabel span2" })
                <p class="formParag">@Model.RequestsLeft</p>
            </div>
            <div class="span10">
                @Html.LabelFor(m => m.Comments, new { @class = "formlabel span2" })
                <p class="formParag">@Model.Comments</p>
            </div>
        </fieldset>
    }
    @using (Html.BeginForm("ApproveBiddingRequest", "BiddingRequests", FormMethod.Post, null))
    {
        <fieldset>
            <legend>Request Status</legend>
            <div class="span10">
                @Html.LabelFor(m => m.Status, new { @class = "formlabel span2" })
                @Html.DropDownListFor(model => model.Status, SelectListItemsForHelper.SelectListItemsFor(Model.Status), new { @class = "x-large" })
                @Html.ValidationMessageFor(m => m.Status)
            </div>
        </fieldset>
    }

</div>
@section FormFooter
{
    <a href="javascript:window.close()">
        <img alt="Close" src="/Content/Images/FoxClose.gif" />
        Close</a>
    <a href="#" id="FormSubmit">Save</a>
    <div id="progressSpan" class="Progress" data-success="@Url.Content("~/Content/Succeeded.gif")" style="display: none;">
        <span id="progressText"></span>
        <img id="progressImg" alt="" src="@Url.Content("~/Content/InProcess.gif")">
    </div>
    @*<a href="#"  onclick="document.forms[0].submit()">Save</a>*@


}

<script type="text/javascript">
    $(function () {
        $('.datepicker').datepicker({
            format: "dd/mm/yyyy",
            todayBtn: true,
            clearBtn: true
        });
    });
</script>

FoxConcept/Views/BiddingRequests/EditBiddingRequest.cshtml
@model FoxConcept.Models.ViewModels.BiddingRequests.BiddingRequestViewModel
@{
    ViewBag.Title = "Edit Bidding Request - " + Model.BiddingRule.Name;
    Layout = "~/Views/Shared/_FoxFormLayout.cshtml";
}
@section scripts
{
    <script src="@Url.Content("~/Scripts/jquery.validate.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/FormAjax.js")" type="text/javascript"></script>
}
@section FormHeader
{
    <span>@ViewBag.Title</span>
    @*<link href="/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />*@
    <link href="/Content/datepicker3.css" rel="stylesheet" type="text/css" />
}

<div class="container">
    @using (Html.BeginForm("EditBiddingRequest", "BiddingRequests", FormMethod.Post, null))
    {
        <fieldset>
            <legend>Request Details</legend>
            @Html.HiddenFor(m => m.InstructorID)
            @Html.HiddenFor(m => m.BiddingRuleID)
            @Html.HiddenFor(m => m.ID)

            <div class="span10">
                @Html.LabelFor(m => m.BiddingPeriodID, new { @class = "span2" })
                @Html.DropDownListFor(m => m.BiddingPeriodID, new SelectList(Model.BiddingPeriods, "ID", "BiddingPeriodString"), new { @class = "x-large" })
                @Html.ValidationMessageFor(m => m.BiddingPeriodID)
            </div>

            <div class="span10">
                @Html.LabelFor(m => m.StartDate, new { @class = "span2" })
                @Html.TextBoxFor(m => m.StartDate, new { @class = "x-large datepicker", @Value = (Model.StartDate).ToString("MM/dd/yyyy") })
                @Html.ValidationMessageFor(m => m.StartDate)
            </div>

            <div class="span10">
                @Html.LabelFor(m => m.EndDate, new { @class = "span2" })
                @Html.TextBoxFor(m => m.EndDate, new { @class = "x-large datepicker", @Value = ((DateTime)Model.EndDate).ToString("MM/dd/yyyy") })
                @Html.ValidationMessageFor(m => m.EndDate)

            </div>
            <div class="span10">
                @Html.LabelFor(m => m.Priority, new { @class = "span2" })
                @Html.TextBoxFor(m => m.Priority, new { @class = "x-large " })
                @Html.ValidationMessageFor(m => m.Priority)
            </div>
            <div class="span10">
                @Html.LabelFor(m => m.Comments, new { @class = "span2" })
                @Html.TextAreaFor(m => m.Comments, new { @class = "x-large " })
                @Html.ValidationMessageFor(m => m.Comments)
            </div>
        </fieldset>
    }

</div>
@section FormFooter
{
    <a href="javascript:window.close()">
        <img alt="Close" src="/Content/Images/FoxClose.gif" />
        Close</a>
    <a href="#" id="FormSubmit">Save</a>
    <div id="progressSpan" class="Progress" data-success="@Url.Content("~/Content/Succeeded.gif")" style="display: none;">
        <span id="progressText"></span>
        <img id="progressImg" alt="" src="@Url.Content("~/Content/InProcess.gif")">
    </div>
    @*<a href="#"  onclick="document.forms[0].submit()">Save</a>*@


}

<script type="text/javascript">
    $(function () {
        $('.datepicker').datepicker({
            format: "dd/mm/yyyy",
            todayBtn: true,
            clearBtn: true
        });
    });
</script>

FoxConcept/Views/BiddingRequests/GetBiddingManagement.cshtml
@model FoxConcept.Models.ViewModels.BiddingRequests.BiddingManagementViewModel
@{
    ViewBag.Title = "Bidding Requests Management";
    Layout = "~/Views/Shared/_FoxPageLayout.cshtml";

    var requests = Model.BiddingRequests.GroupBy(b => b.BiddingPeriodID, b => b, (key, g) => new
    {
        RuleID = key,
        BiddingRuleName = g.FirstOrDefault().BiddingPeriod.BiddingPeriodString,
        BiddingRequests = g.ToList()
    });
}
@section Header
{
    <link href="/Content/dropit.css" rel="stylesheet" type="text/css" />
}
<div class="container scrollable">
    @using (Html.BeginForm("GetBiddingManagement", "BiddingRequests", FormMethod.Post, null))
    {
        <fieldset>
            <legend>Filter Bidding Requests</legend>
            <div class="span10">
                @Html.LabelFor(m => m.InstructorID, new { @class = "span1" })
                @Html.DropDownListFor(m => m.InstructorID, new SelectList(Model.Instructors, "ID", "Name", "Select a Value"), new { @class = "x-large" })
            </div>

            <div class="span10">
                @Html.LabelFor(m => m.BiddingPeriodID, new { @class = "span1" })
                @Html.DropDownListFor(m => m.BiddingPeriodID, new SelectList(Model.BiddingPeriods, "ID", "Name", "Select a Value"), new { @class = "x-large" })
                <input type="submit" value="Search" class="button width-70"/>
            </div>
        </fieldset>
    }
</div>
<div class="container scrollable height90">


    <table>
        <thead>
            <tr>
                <th width="2%">&nbsp;</th>
                <th width="13%">Bidder</th>
                <th width="15%">Bidding Type</th>
                @*<th width="20%">Bidding Rule</th>*@
                <th width="10%">Start Date</th>
                <th width="10%">End Date</th>
                <th width="10%">Priority</th>
                <th width="30%">Comments</th>
                <th width="10%">Status</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var header in requests)
            {
                <tr class="header" data-state="open">
                    <td>
                        <img src="@Url.Content("~/Content/Images/bullet_toggle_minus.png")" class="pointer" alt="collapse"/></td>
                    <td colspan="7">@header.BiddingRuleName</td>
                </tr>
                if (header.BiddingRequests.Count() > 0)
                {
                    foreach (var row in header.BiddingRequests)
                    {
                <tr>
                    <td>
                        <ul class="menu dropit">
                            <li>
                                <a href="#">
                                    <img src='/Content/Images/edit.gif' alt='Edit' /></a>
                                <ul class="dropit-submenu-left">
                                    <li>@Html.NewWindowActionLink(String.Format("ApproveBiddingRequest/{0}", row.ID.ToString()), "BiddingRequests", "Review Request", null, false)</li>
                                    <li>@Html.ActionLink("Delete", "DeleteBiddingRequest", new { @ID = row.ID })</li>
                                </ul>
                            </li>
                        </ul>
                    </td>
                    <td>@row.InstructorName</td>
                    <td>@row.BiddingRule.Name</td>
                    <td>@row.StartDate.ToString("dd/MM/yyyy")</td>
                    <td>@{
                        var enddate = row.EndDate != null ? ((DateTime)row.EndDate).ToString("dd/MM/yyyy") : String.Empty;
                    }@enddate</td>
                    <td>@row.Priority</td>
                    <td>@row.Comments</td>
                    <td>@row.Status</td>
                </tr>
                    }
                }

            }
        </tbody>

    </table>
</div>
@section Footer
{
    <script src="/Scripts/Dropit/dropit.js" type="text/javascript"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $('.menu').dropit();

        $('.header').click(function () {

            var elementState = $(this).attr("data-state");
            if (elementState == "open") {
                $(this).find('.pointer').attr('src', '@Url.Content("~/Content/Images/bullet_toggle_plus.png")');
                $(this).attr("data-state", "close");
            } else {
                $(this).find('.pointer').attr('src', '@Url.Content("~/Content/Images/bullet_toggle_minus.png")');
                $(this).attr("data-state", "open");
            }


            $(this).nextUntil('tr.header').slideToggle(150, function () {
            });
        });

    });
</script>